### ISSUE TITLE
proxy-volume secret as optional for oidc authentication

### ISSUE THREAD

**Issue by robbarnsley** [rucio/helm-charts#113]
The existence of an x509 user proxy at `/opt/proxy` currently takes precedence in gfal2 operations even if a bearer token is set in the environment. This should be an optional secret:

https://github.com/rucio/helm-charts/blob/3f757838cce015f014e3aa5fa4f4392ba702329b/charts/rucio-daemons/templates/reaper.yaml#L71-L73

(and presumably for the other services too)

**Comment by rcarpa** [comment]
https://github.com/rucio/helm-charts/pull/139 Includes a commit which may interest you, so your opinion on that PR is welcomed :)
