### ISSUE TITLE
Allow server pod Prometheus metrics to be enabled independently of creation of a ServiceMonitor

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/helm-charts#181]
With the helm charts for the daemons it is possible to enable Prometheus metrics for a Pod [independently of the ServiceMonitor prometheus-operator CRD](https://github.com/rucio/helm-charts/blob/d0dae215c749ae651011310d5fae693316dc99f2/charts/rucio-daemons/templates/servicemonitor.yaml#L1). 

The server is [unable to make this distinction](https://github.com/rucio/helm-charts/blob/d0dae215c749ae651011310d5fae693316dc99f2/charts/rucio-server/templates/servicemonitor.yaml#L2).

**Comment by bjwhite-fnal** [comment]
@bari12 I'm not sure if you saw that I have a PR open for someone to look at: https://github.com/rucio/helm-charts/pull/182

**Comment by bari12** [comment]
I saw, I was hoping that one of the helm-charts experts reviews this :-)

**Comment by bjwhite-fnal** [comment]
Hey, @ericvaandering could you take a look at this?

**Comment by ericvaandering** [comment]
I think this is going to be fine. I need to educate myself what a service monitor IS first.
