### ISSUE TITLE
PR #185 breaks WebUI for CMS

### ISSUE THREAD

**Issue by ericvaandering** [rucio/helm-charts#198]
See the comments at the end of PR 185.

**Comment by ericvaandering** [comment]
@maany any thought on this?

**Comment by maany** [comment]
@ericvaandering I believe I had removed the following from the UI helm charts

https://github.com/rucio/helm-charts/pull/185/files#diff-bc71ecc0f1e227906b2b5c8472089cdbe63d3115158fddc6b74044c8758b0497L159-L160

```
            - name: RUCIO_DEFINE_ALIASES
              value: "True"
```

as I could not find where it was used in the containers to configure apache or anything else:

https://github.com/rucio/containers/blob/925b1f7f76fd346e96abc039a3771c4ddb8062da/ui/rucio.conf.j2  ( snapshot of containers from before I made any changes related to the #185 )

--- 

I can update the helm chart to allow you to set the `RUCIO_DEFINE_ALIASES` environment variable for the UI pods. However, it looks like the UI container does not really do anything with this environment variable.


Looking at the server containers, I did find that we update the apache config based on the `RUCIO_DEFINE_ALIASES` environment variable.
```
{% if RUCIO_DEFINE_ALIASES|default('False') == 'True' %}
 Include /opt/rucio/etc/aliases.conf
{% endif %}
```

I could do something similar for the UI containers, but as I do not know what exactly is breaking for you, I cannot say if doing this will fix your deployment. Could you give me more info on what is breaking or whether you think updating the helm charts and the containers as I have described above should fix the issue?

**Comment by ericvaandering** [comment]
I found an issue on my side. The ingress port reverted to 80, so I need to directly set it to 443. Maybe update the release notes, but no code changes are needed

**Comment by maany** [comment]
Thanks @ericvaandering, I'll look into the ingress config
