### ISSUE TITLE
Fix server pod restarts when errorLogExporter is unready

### ISSUE THREAD

**Issue by astroclark** [rucio/helm-charts#88]
A minor irritation: I've noted that my server/auth-server pods usually go through 2 restarts before coming up.  The cause is actually the busybox error log exporter is looking for logs which do not yet exist:
```
    $  k logs rucio-server-c54bb8967-fpgqd -c httpd-error-log --previous
    tail: can't open '/var/log/httpd/error_log': No such file or directory
    tail: no files
```
It's not a big problem but means the pods show restarts when, in fact, there are no problems.

A trivial solution: prefix the busybox container cmd to create that file:
```
touch /var/log/httpd/error_log ; tail -n+1 -f /var/log/httpd/error_log
```
This seems to eliminate that problem and the pods now come up cleanly.  I'll hold off opening a PR in case there's some downside or a smarter solution like a preStart hook is preferred.

**Comment by bari12** [comment]
Maybe @rcarpa or @ericvaandering have a comment?

**Comment by rcarpa** [comment]
Thanks for investigating the issue. We saw the problem on our side too, but never prioritized it enough to  investigate it.

I've seen that tail has an option "--retry"; did you try using it?
